name: Add Docs Messages

on:
  push:
    branches:
      - main
    paths:
      - 'modDocs/src/*/*.mdx'

jobs:
  comment_on_commit:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: 1
          body: |
            ${{ github.event.head_commit.id }}: ${{ github.event.head_commit.message }}
